version: "3"

services:
  jalasoft_backend:
    image: jalasoft_backend
    container_name: cms-nft-minting-app
    ports:
      - "8082:80"
    volumes:
      - .:/usr/src/app
      - .env:/usr/src/app/swagger_server/.env
    environment:
      - FLASK_PORT=80
      - FLASK_HOST="0.0.0.0"
      - FLASK_DEBUG=True
      - DB=mysql
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_SCHEMA=jalasoft
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SHOW_SQL_QUERIES=False
      - FLASK_ENV=development
      - JWT_SECRET=hHHpLuOJA6Tfh6ruMycVmn95otboWQ2U5ZQI8SJv2v0n3iCe1MB5L75ZVRFu8q3C
      - JWT_ALGORITHM=HS256
    restart: always
  jalasoft_db:
    image: mariadb
    container_name: cms-nft-minting-db
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
    restart: always

networks:
  default:
    name: cms-backend_backend
    external: true
