# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        code: int = None,
        message: str = None,
        data: object = None,
        error: str = None,
    ):  # noqa: E501
        """ApiResponse - a model defined in Swagger

        :param code: The code of this ApiResponse.  # noqa: E501
        :type code: int
        :param message: The message of this ApiResponse.  # noqa: E501
        :type message: str
        :param data: The data of this ApiResponse.  # noqa: E501
        :type data: object
        :param error: The error of this ApiResponse.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {"code": int, "message": str, "data": object, "error": str}

        self.attribute_map = {
            "code": "code",
            "message": "message",
            "data": "data",
            "error": "error",
        }
        self._code = code
        self._message = message
        self._data = data
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> "ApiResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponse of this ApiResponse.  # noqa: E501
        :rtype: ApiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ApiResponse.


        :return: The code of this ApiResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ApiResponse.


        :param code: The code of this ApiResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ApiResponse.


        :return: The message of this ApiResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ApiResponse.


        :param message: The message of this ApiResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> object:
        """Gets the data of this ApiResponse.


        :return: The data of this ApiResponse.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this ApiResponse.


        :param data: The data of this ApiResponse.
        :type data: object
        """

        self._data = data

    @property
    def error(self) -> str:
        """Gets the error of this ApiResponse.


        :return: The error of this ApiResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this ApiResponse.


        :param error: The error of this ApiResponse.
        :type error: str
        """

        self._error = error
