# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.collection_off_chain_metadata import (
    CollectionOffChainMetadata,
)  # noqa: F401,E501
from swagger_server import util


class BaseCollection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        name: str = None,
        off_chain_metadata: CollectionOffChainMetadata = None,
        short_word: str = None,
        publish_time: datetime = None,
    ):  # noqa: E501
        """BaseCollection - a model defined in Swagger

        :param name: The name of this BaseCollection.  # noqa: E501
        :type name: str
        :param off_chain_metadata: The off_chain_metadata of this BaseCollection.  # noqa: E501
        :type off_chain_metadata: CollectionOffChainMetadata
        :param short_word: The short_word of this BaseCollection.  # noqa: E501
        :type short_word: str
        :param publish_time: The publish_time of this BaseCollection.  # noqa: E501
        :type publish_time: datetime
        """
        self.swagger_types = {
            "name": str,
            "off_chain_metadata": CollectionOffChainMetadata,
            "short_word": str,
            "publish_time": datetime,
        }

        self.attribute_map = {
            "name": "name",
            "off_chain_metadata": "off_chain_metadata",
            "short_word": "short_word",
            "publish_time": "publish_time",
        }
        self._name = name
        self._off_chain_metadata = off_chain_metadata
        self._short_word = short_word
        self._publish_time = publish_time

    @classmethod
    def from_dict(cls, dikt) -> "BaseCollection":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseCollection of this BaseCollection.  # noqa: E501
        :rtype: BaseCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BaseCollection.


        :return: The name of this BaseCollection.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BaseCollection.


        :param name: The name of this BaseCollection.
        :type name: str
        """

        self._name = name

    @property
    def off_chain_metadata(self) -> CollectionOffChainMetadata:
        """Gets the off_chain_metadata of this BaseCollection.


        :return: The off_chain_metadata of this BaseCollection.
        :rtype: CollectionOffChainMetadata
        """
        return self._off_chain_metadata

    @off_chain_metadata.setter
    def off_chain_metadata(self, off_chain_metadata: CollectionOffChainMetadata):
        """Sets the off_chain_metadata of this BaseCollection.


        :param off_chain_metadata: The off_chain_metadata of this BaseCollection.
        :type off_chain_metadata: CollectionOffChainMetadata
        """

        self._off_chain_metadata = off_chain_metadata

    @property
    def short_word(self) -> str:
        """Gets the short_word of this BaseCollection.


        :return: The short_word of this BaseCollection.
        :rtype: str
        """
        return self._short_word

    @short_word.setter
    def short_word(self, short_word: str):
        """Sets the short_word of this BaseCollection.


        :param short_word: The short_word of this BaseCollection.
        :type short_word: str
        """

        self._short_word = short_word

    @property
    def publish_time(self) -> datetime:
        """Gets the publish_time of this BaseCollection.


        :return: The publish_time of this BaseCollection.
        :rtype: datetime
        """
        return self._publish_time

    @publish_time.setter
    def publish_time(self, publish_time: datetime):
        """Sets the publish_time of this BaseCollection.


        :param publish_time: The publish_time of this BaseCollection.
        :type publish_time: datetime
        """

        self._publish_time = publish_time
