# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BaseSerie(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        name: str = None,
        description: str = None,
        short_word: str = None,
        publish_time: datetime = None,
    ):  # noqa: E501
        """BaseSerie - a model defined in Swagger

        :param name: The name of this BaseSerie.  # noqa: E501
        :type name: str
        :param description: The description of this BaseSerie.  # noqa: E501
        :type description: str
        :param short_word: The short_word of this BaseSerie.  # noqa: E501
        :type short_word: str
        :param publish_time: The publish_time of this BaseSerie.  # noqa: E501
        :type publish_time: datetime
        """
        self.swagger_types = {
            "name": str,
            "description": str,
            "short_word": str,
            "publish_time": datetime,
        }

        self.attribute_map = {
            "name": "name",
            "description": "description",
            "short_word": "short_word",
            "publish_time": "publish_time",
        }
        self._name = name
        self._description = description
        self._short_word = short_word
        self._publish_time = publish_time

    @classmethod
    def from_dict(cls, dikt) -> "BaseSerie":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseSerie of this BaseSerie.  # noqa: E501
        :rtype: BaseSerie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BaseSerie.


        :return: The name of this BaseSerie.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BaseSerie.


        :param name: The name of this BaseSerie.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this BaseSerie.


        :return: The description of this BaseSerie.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BaseSerie.


        :param description: The description of this BaseSerie.
        :type description: str
        """

        self._description = description

    @property
    def short_word(self) -> str:
        """Gets the short_word of this BaseSerie.


        :return: The short_word of this BaseSerie.
        :rtype: str
        """
        return self._short_word

    @short_word.setter
    def short_word(self, short_word: str):
        """Sets the short_word of this BaseSerie.


        :param short_word: The short_word of this BaseSerie.
        :type short_word: str
        """

        self._short_word = short_word

    @property
    def publish_time(self) -> datetime:
        """Gets the publish_time of this BaseSerie.


        :return: The publish_time of this BaseSerie.
        :rtype: datetime
        """
        return self._publish_time

    @publish_time.setter
    def publish_time(self, publish_time: datetime):
        """Sets the publish_time of this BaseSerie.


        :param publish_time: The publish_time of this BaseSerie.
        :type publish_time: datetime
        """

        self._publish_time = publish_time
