# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.edition_off_chain_metadata import (
    EditionOffChainMetadata,
)  # noqa: F401,E501
from swagger_server import util


class BaseEdition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        name: str = None,
        off_chain_metadata: EditionOffChainMetadata = None,
        publish_time: datetime = None,
        avatar_wearable_id: int = None,
    ):  # noqa: E501
        """BaseEdition - a model defined in Swagger

        :param name: The name of this BaseEdition.  # noqa: E501
        :type name: str
        :param off_chain_metadata: The off_chain_metadata of this BaseEdition.  # noqa: E501
        :type off_chain_metadata: EditionOffChainMetadata
        :param publish_time: The publish_time of this BaseEdition.  # noqa: E501
        :type publish_time: datetime
        :param avatar_wearable_id: The avatar_wearable_id of this BaseEdition.  # noqa: E501
        :type avatar_wearable_id: int
        """
        self.swagger_types = {
            "name": str,
            "off_chain_metadata": EditionOffChainMetadata,
            "publish_time": datetime,
            "avatar_wearable_id": int,
        }

        self.attribute_map = {
            "name": "name",
            "off_chain_metadata": "off_chain_metadata",
            "publish_time": "publish_time",
            "avatar_wearable_id": "avatar_wearable_id",
        }
        self._name = name
        self._off_chain_metadata = off_chain_metadata
        self._publish_time = publish_time
        self._avatar_wearable_id = avatar_wearable_id

    @classmethod
    def from_dict(cls, dikt) -> "BaseEdition":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseEdition of this BaseEdition.  # noqa: E501
        :rtype: BaseEdition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BaseEdition.


        :return: The name of this BaseEdition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BaseEdition.


        :param name: The name of this BaseEdition.
        :type name: str
        """

        self._name = name

    @property
    def off_chain_metadata(self) -> EditionOffChainMetadata:
        """Gets the off_chain_metadata of this BaseEdition.


        :return: The off_chain_metadata of this BaseEdition.
        :rtype: EditionOffChainMetadata
        """
        return self._off_chain_metadata

    @off_chain_metadata.setter
    def off_chain_metadata(self, off_chain_metadata: EditionOffChainMetadata):
        """Sets the off_chain_metadata of this BaseEdition.


        :param off_chain_metadata: The off_chain_metadata of this BaseEdition.
        :type off_chain_metadata: EditionOffChainMetadata
        """

        self._off_chain_metadata = off_chain_metadata

    @property
    def publish_time(self) -> datetime:
        """Gets the publish_time of this BaseEdition.


        :return: The publish_time of this BaseEdition.
        :rtype: datetime
        """
        return self._publish_time

    @publish_time.setter
    def publish_time(self, publish_time: datetime):
        """Sets the publish_time of this BaseEdition.


        :param publish_time: The publish_time of this BaseEdition.
        :type publish_time: datetime
        """

        self._publish_time = publish_time

    @property
    def avatar_wearable_id(self) -> int:
        """Gets the avatar_wearable_id of this BaseEdition.


        :return: The avatar_wearable_id of this BaseEdition.
        :rtype: int
        """
        return self._avatar_wearable_id

    @avatar_wearable_id.setter
    def avatar_wearable_id(self, avatar_wearable_id: int):
        """Sets the avatar_wearable_id of this BaseEdition.


        :param avatar_wearable_id: The avatar_wearable_id of this BaseEdition.
        :type avatar_wearable_id: int
        """

        self._avatar_wearable_id = avatar_wearable_id
