# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CollectionOffChainMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str = None):  # noqa: E501
        """CollectionOffChainMetadata - a model defined in Swagger

        :param description: The description of this CollectionOffChainMetadata.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {"description": str}

        self.attribute_map = {"description": "description"}
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> "CollectionOffChainMetadata":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CollectionOffChainMetadata of this CollectionOffChainMetadata.  # noqa: E501
        :rtype: CollectionOffChainMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this CollectionOffChainMetadata.


        :return: The description of this CollectionOffChainMetadata.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CollectionOffChainMetadata.


        :param description: The description of this CollectionOffChainMetadata.
        :type description: str
        """

        self._description = description
