# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_collection import BaseCollection  # noqa: F401,E501
from swagger_server.models.collection_off_chain_metadata import (
    CollectionOffChainMetadata,
)  # noqa: F401,E501
from swagger_server.models.collection_status import CollectionStatus  # noqa: F401,E501
from swagger_server.models.edition_listable import EditionListable  # noqa: F401,E501
from swagger_server.models.serie_listable import SerieListable  # noqa: F401,E501
from swagger_server import util


class Collection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        name: str = None,
        off_chain_metadata: CollectionOffChainMetadata = None,
        short_word: str = None,
        publish_time: datetime = None,
        id: int = None,
        status: CollectionStatus = None,
        serie: SerieListable = None,
        editions: List[EditionListable] = None,
        wearables_count: int = None,
        has_published_editions: bool = None,
    ):  # noqa: E501
        """Collection - a model defined in Swagger

        :param name: The name of this Collection.  # noqa: E501
        :type name: str
        :param off_chain_metadata: The off_chain_metadata of this Collection.  # noqa: E501
        :type off_chain_metadata: CollectionOffChainMetadata
        :param short_word: The short_word of this Collection.  # noqa: E501
        :type short_word: str
        :param publish_time: The publish_time of this Collection.  # noqa: E501
        :type publish_time: datetime
        :param id: The id of this Collection.  # noqa: E501
        :type id: int
        :param status: The status of this Collection.  # noqa: E501
        :type status: CollectionStatus
        :param serie: The serie of this Collection.  # noqa: E501
        :type serie: SerieListable
        :param editions: The editions of this Collection.  # noqa: E501
        :type editions: List[EditionListable]
        :param wearables_count: The wearables_count of this Collection.  # noqa: E501
        :type wearables_count: int
        :param has_published_editions: The has_published_editions of this Collection.  # noqa: E501
        :type has_published_editions: bool
        """
        self.swagger_types = {
            "name": str,
            "off_chain_metadata": CollectionOffChainMetadata,
            "short_word": str,
            "publish_time": datetime,
            "id": int,
            "status": CollectionStatus,
            "serie": SerieListable,
            "editions": List[EditionListable],
            "wearables_count": int,
            "has_published_editions": bool,
        }

        self.attribute_map = {
            "name": "name",
            "off_chain_metadata": "off_chain_metadata",
            "short_word": "short_word",
            "publish_time": "publish_time",
            "id": "id",
            "status": "status",
            "serie": "serie",
            "editions": "editions",
            "wearables_count": "wearables_count",
            "has_published_editions": "has_published_editions",
        }
        self._name = name
        self._off_chain_metadata = off_chain_metadata
        self._short_word = short_word
        self._publish_time = publish_time
        self._id = id
        self._status = status
        self._serie = serie
        self._editions = editions
        self._wearables_count = wearables_count
        self._has_published_editions = has_published_editions

    @classmethod
    def from_dict(cls, dikt) -> "Collection":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Collection of this Collection.  # noqa: E501
        :rtype: Collection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Collection.


        :return: The name of this Collection.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Collection.


        :param name: The name of this Collection.
        :type name: str
        """

        self._name = name

    @property
    def off_chain_metadata(self) -> CollectionOffChainMetadata:
        """Gets the off_chain_metadata of this Collection.


        :return: The off_chain_metadata of this Collection.
        :rtype: CollectionOffChainMetadata
        """
        return self._off_chain_metadata

    @off_chain_metadata.setter
    def off_chain_metadata(self, off_chain_metadata: CollectionOffChainMetadata):
        """Sets the off_chain_metadata of this Collection.


        :param off_chain_metadata: The off_chain_metadata of this Collection.
        :type off_chain_metadata: CollectionOffChainMetadata
        """

        self._off_chain_metadata = off_chain_metadata

    @property
    def short_word(self) -> str:
        """Gets the short_word of this Collection.


        :return: The short_word of this Collection.
        :rtype: str
        """
        return self._short_word

    @short_word.setter
    def short_word(self, short_word: str):
        """Sets the short_word of this Collection.


        :param short_word: The short_word of this Collection.
        :type short_word: str
        """

        self._short_word = short_word

    @property
    def publish_time(self) -> datetime:
        """Gets the publish_time of this Collection.


        :return: The publish_time of this Collection.
        :rtype: datetime
        """
        return self._publish_time

    @publish_time.setter
    def publish_time(self, publish_time: datetime):
        """Sets the publish_time of this Collection.


        :param publish_time: The publish_time of this Collection.
        :type publish_time: datetime
        """

        self._publish_time = publish_time

    @property
    def id(self) -> int:
        """Gets the id of this Collection.


        :return: The id of this Collection.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Collection.


        :param id: The id of this Collection.
        :type id: int
        """

        self._id = id

    @property
    def status(self) -> CollectionStatus:
        """Gets the status of this Collection.


        :return: The status of this Collection.
        :rtype: CollectionStatus
        """
        return self._status

    @status.setter
    def status(self, status: CollectionStatus):
        """Sets the status of this Collection.


        :param status: The status of this Collection.
        :type status: CollectionStatus
        """

        self._status = status

    @property
    def serie(self) -> SerieListable:
        """Gets the serie of this Collection.


        :return: The serie of this Collection.
        :rtype: SerieListable
        """
        return self._serie

    @serie.setter
    def serie(self, serie: SerieListable):
        """Sets the serie of this Collection.


        :param serie: The serie of this Collection.
        :type serie: SerieListable
        """

        self._serie = serie

    @property
    def editions(self) -> List[EditionListable]:
        """Gets the editions of this Collection.


        :return: The editions of this Collection.
        :rtype: List[EditionListable]
        """
        return self._editions

    @editions.setter
    def editions(self, editions: List[EditionListable]):
        """Sets the editions of this Collection.


        :param editions: The editions of this Collection.
        :type editions: List[EditionListable]
        """

        self._editions = editions

    @property
    def wearables_count(self) -> int:
        """Gets the wearables_count of this Collection.

        The amount of wearables in the Collection (cannot be deleted if this is > 0)  # noqa: E501

        :return: The wearables_count of this Collection.
        :rtype: int
        """
        return self._wearables_count

    @wearables_count.setter
    def wearables_count(self, wearables_count: int):
        """Sets the wearables_count of this Collection.

        The amount of wearables in the Collection (cannot be deleted if this is > 0)  # noqa: E501

        :param wearables_count: The wearables_count of this Collection.
        :type wearables_count: int
        """

        self._wearables_count = wearables_count

    @property
    def has_published_editions(self) -> bool:
        """Gets the has_published_editions of this Collection.

        Whether the Collection has published Editions (short_word cannot be updated if this is true)  # noqa: E501

        :return: The has_published_editions of this Collection.
        :rtype: bool
        """
        return self._has_published_editions

    @has_published_editions.setter
    def has_published_editions(self, has_published_editions: bool):
        """Sets the has_published_editions of this Collection.

        Whether the Collection has published Editions (short_word cannot be updated if this is true)  # noqa: E501

        :param has_published_editions: The has_published_editions of this Collection.
        :type has_published_editions: bool
        """

        self._has_published_editions = has_published_editions
