# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditionDesignSlot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, edition_design_slot: List[str] = None):  # noqa: E501
        """EditionDesignSlot - a model defined in Swagger

        :param edition_design_slot: The edition_design_slot of this EditionDesignSlot.  # noqa: E501
        :type edition_design_slot: List[str]
        """
        self.swagger_types = {"edition_design_slot": List[str]}

        self.attribute_map = {"edition_design_slot": "EDITION_DESIGN_SLOT"}
        self._edition_design_slot = edition_design_slot

    @classmethod
    def from_dict(cls, dikt) -> "EditionDesignSlot":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditionDesignSlot of this EditionDesignSlot.  # noqa: E501
        :rtype: EditionDesignSlot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edition_design_slot(self) -> List[str]:
        """Gets the edition_design_slot of this EditionDesignSlot.


        :return: The edition_design_slot of this EditionDesignSlot.
        :rtype: List[str]
        """
        return self._edition_design_slot

    @edition_design_slot.setter
    def edition_design_slot(self, edition_design_slot: List[str]):
        """Sets the edition_design_slot of this EditionDesignSlot.


        :param edition_design_slot: The edition_design_slot of this EditionDesignSlot.
        :type edition_design_slot: List[str]
        """

        self._edition_design_slot = edition_design_slot
