# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditionStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DRAFT = "DRAFT"
    CREATING = "CREATING"
    CREATED = "CREATED"
    MINTED = "MINTED"
    ON_SALE = "ON_SALE"
    ERROR = "ERROR"

    def __init__(self):  # noqa: E501
        """EditionStatus - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "EditionStatus":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditionStatus of this EditionStatus.  # noqa: E501
        :rtype: EditionStatus
        """
        return util.deserialize_model(dikt, cls)
