# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditionTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, edition_types: List[str] = None):  # noqa: E501
        """EditionTypes - a model defined in Swagger

        :param edition_types: The edition_types of this EditionTypes.  # noqa: E501
        :type edition_types: List[str]
        """
        self.swagger_types = {"edition_types": List[str]}

        self.attribute_map = {"edition_types": "EDITION_TYPES"}
        self._edition_types = edition_types

    @classmethod
    def from_dict(cls, dikt) -> "EditionTypes":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditionTypes of this EditionTypes.  # noqa: E501
        :rtype: EditionTypes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edition_types(self) -> List[str]:
        """Gets the edition_types of this EditionTypes.


        :return: The edition_types of this EditionTypes.
        :rtype: List[str]
        """
        return self._edition_types

    @edition_types.setter
    def edition_types(self, edition_types: List[str]):
        """Sets the edition_types of this EditionTypes.


        :param edition_types: The edition_types of this EditionTypes.
        :type edition_types: List[str]
        """

        self._edition_types = edition_types
