# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditionType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NIL = "EDITION_TYPE_AVATAR_NIL"
    STATUE = "EDITION_TYPE_AVATAR_STATUE"
    WEARABLE = "EDITION_TYPE_AVATAR_WEARABLE"

    def __init__(self):  # noqa: E501
        """EditionType - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "EditionType":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditionType of this EditionType.  # noqa: E501
        :rtype: EditionType
        """
        return util.deserialize_model(dikt, cls)
