# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditionRarity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, edition_rarity: List[str] = None):  # noqa: E501
        """EditionRarity - a model defined in Swagger

        :param edition_rarity: The edition_rarity of this EditionRarity.  # noqa: E501
        :type edition_rarity: List[str]
        """
        self.swagger_types = {"edition_rarity": List[str]}

        self.attribute_map = {"edition_rarity": "EDITION_RARITY"}
        self._edition_rarity = edition_rarity

    @classmethod
    def from_dict(cls, dikt) -> "EditionRarity":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditionRarity of this EditionRarity.  # noqa: E501
        :rtype: EditionRarity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edition_rarity(self) -> List[str]:
        """Gets the edition_rarity of this EditionRarity.


        :return: The edition_rarity of this EditionRarity.
        :rtype: List[str]
        """
        return self._edition_rarity

    @edition_rarity.setter
    def edition_rarity(self, edition_rarity: List[str]):
        """Sets the edition_rarity of this EditionRarity.


        :param edition_rarity: The edition_rarity of this EditionRarity.
        :type edition_rarity: List[str]
        """

        self._edition_rarity = edition_rarity
