# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_edition import BaseEdition  # noqa: F401,E501
from swagger_server.models.collection_listable import (
    CollectionListable,
)  # noqa: F401,E501
from swagger_server.models.drop_edition import DropEdition  # noqa: F401,E501
from swagger_server.models.edition_off_chain_metadata import (
    EditionOffChainMetadata,
)  # noqa: F401,E501
from swagger_server.models.edition_on_chain_metadata import (
    EditionOnChainMetadata,
)  # noqa: F401,E501
from swagger_server.models.edition_status import EditionStatus  # noqa: F401,E501
from swagger_server.models.nft import Nft  # noqa: F401,E501
from swagger_server import util


class Edition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        name: str = None,
        off_chain_metadata: EditionOffChainMetadata = None,
        publish_time: datetime = None,
        avatar_wearable_id: int = None,
        id: int = None,
        on_chain_metadata: EditionOnChainMetadata = None,
        status: EditionStatus = None,
        price: str = None,
        reserve_percentage: str = None,
        collection: CollectionListable = None,
        drop_editions: List[DropEdition] = None,
        nfts: List[Nft] = None,
        nfts_minted: int = None,
        nfts_for_sale: int = None,
    ):  # noqa: E501
        """Edition - a model defined in Swagger

        :param name: The name of this Edition.  # noqa: E501
        :type name: str
        :param off_chain_metadata: The off_chain_metadata of this Edition.  # noqa: E501
        :type off_chain_metadata: EditionOffChainMetadata
        :param publish_time: The publish_time of this Edition.  # noqa: E501
        :type publish_time: datetime
        :param avatar_wearable_id: The avatar_wearable_id of this Edition.  # noqa: E501
        :type avatar_wearable_id: int
        :param id: The id of this Edition.  # noqa: E501
        :type id: int
        :param on_chain_metadata: The on_chain_metadata of this Edition.  # noqa: E501
        :type on_chain_metadata: EditionOnChainMetadata
        :param status: The status of this Edition.  # noqa: E501
        :type status: EditionStatus
        :param price: The price of this Edition.  # noqa: E501
        :type price: str
        :param reserve_percentage: The reserve_percentage of this Edition.  # noqa: E501
        :type reserve_percentage: str
        :param collection: The collection of this Edition.  # noqa: E501
        :type collection: CollectionListable
        :param drop_editions: The drop_editions of this Edition.  # noqa: E501
        :type drop_editions: List[DropEdition]
        :param nfts: The nfts of this Edition.  # noqa: E501
        :type nfts: List[Nft]
        :param nfts_minted: The nfts_minted of this Edition.  # noqa: E501
        :type nfts_minted: int
        :param nfts_for_sale: The nfts_for_sale of this Edition.  # noqa: E501
        :type nfts_for_sale: int
        """
        self.swagger_types = {
            "name": str,
            "off_chain_metadata": EditionOffChainMetadata,
            "publish_time": datetime,
            "avatar_wearable_id": int,
            "id": int,
            "on_chain_metadata": EditionOnChainMetadata,
            "status": EditionStatus,
            "price": str,
            "reserve_percentage": str,
            "collection": CollectionListable,
            "drop_editions": List[DropEdition],
            "nfts": List[Nft],
            "nfts_minted": int,
            "nfts_for_sale": int,
        }

        self.attribute_map = {
            "name": "name",
            "off_chain_metadata": "off_chain_metadata",
            "publish_time": "publish_time",
            "avatar_wearable_id": "avatar_wearable_id",
            "id": "id",
            "on_chain_metadata": "on_chain_metadata",
            "status": "status",
            "price": "price",
            "reserve_percentage": "reserve_percentage",
            "collection": "collection",
            "drop_editions": "dropEditions",
            "nfts": "nfts",
            "nfts_minted": "nfts_minted",
            "nfts_for_sale": "nfts_for_sale",
        }
        self._name = name
        self._off_chain_metadata = off_chain_metadata
        self._publish_time = publish_time
        self._avatar_wearable_id = avatar_wearable_id
        self._id = id
        self._on_chain_metadata = on_chain_metadata
        self._status = status
        self._price = price
        self._reserve_percentage = reserve_percentage
        self._collection = collection
        self._drop_editions = drop_editions
        self._nfts = nfts
        self._nfts_minted = nfts_minted
        self._nfts_for_sale = nfts_for_sale

    @classmethod
    def from_dict(cls, dikt) -> "Edition":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Edition of this Edition.  # noqa: E501
        :rtype: Edition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Edition.


        :return: The name of this Edition.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Edition.


        :param name: The name of this Edition.
        :type name: str
        """

        self._name = name

    @property
    def off_chain_metadata(self) -> EditionOffChainMetadata:
        """Gets the off_chain_metadata of this Edition.


        :return: The off_chain_metadata of this Edition.
        :rtype: EditionOffChainMetadata
        """
        return self._off_chain_metadata

    @off_chain_metadata.setter
    def off_chain_metadata(self, off_chain_metadata: EditionOffChainMetadata):
        """Sets the off_chain_metadata of this Edition.


        :param off_chain_metadata: The off_chain_metadata of this Edition.
        :type off_chain_metadata: EditionOffChainMetadata
        """

        self._off_chain_metadata = off_chain_metadata

    @property
    def publish_time(self) -> datetime:
        """Gets the publish_time of this Edition.


        :return: The publish_time of this Edition.
        :rtype: datetime
        """
        return self._publish_time

    @publish_time.setter
    def publish_time(self, publish_time: datetime):
        """Sets the publish_time of this Edition.


        :param publish_time: The publish_time of this Edition.
        :type publish_time: datetime
        """

        self._publish_time = publish_time

    @property
    def avatar_wearable_id(self) -> int:
        """Gets the avatar_wearable_id of this Edition.


        :return: The avatar_wearable_id of this Edition.
        :rtype: int
        """
        return self._avatar_wearable_id

    @avatar_wearable_id.setter
    def avatar_wearable_id(self, avatar_wearable_id: int):
        """Sets the avatar_wearable_id of this Edition.


        :param avatar_wearable_id: The avatar_wearable_id of this Edition.
        :type avatar_wearable_id: int
        """

        self._avatar_wearable_id = avatar_wearable_id

    @property
    def id(self) -> int:
        """Gets the id of this Edition.


        :return: The id of this Edition.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Edition.


        :param id: The id of this Edition.
        :type id: int
        """

        self._id = id

    @property
    def on_chain_metadata(self) -> EditionOnChainMetadata:
        """Gets the on_chain_metadata of this Edition.


        :return: The on_chain_metadata of this Edition.
        :rtype: EditionOnChainMetadata
        """
        return self._on_chain_metadata

    @on_chain_metadata.setter
    def on_chain_metadata(self, on_chain_metadata: EditionOnChainMetadata):
        """Sets the on_chain_metadata of this Edition.


        :param on_chain_metadata: The on_chain_metadata of this Edition.
        :type on_chain_metadata: EditionOnChainMetadata
        """

        self._on_chain_metadata = on_chain_metadata

    @property
    def status(self) -> EditionStatus:
        """Gets the status of this Edition.


        :return: The status of this Edition.
        :rtype: EditionStatus
        """
        return self._status

    @status.setter
    def status(self, status: EditionStatus):
        """Sets the status of this Edition.


        :param status: The status of this Edition.
        :type status: EditionStatus
        """

        self._status = status

    @property
    def price(self) -> str:
        """Gets the price of this Edition.


        :return: The price of this Edition.
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price: str):
        """Sets the price of this Edition.


        :param price: The price of this Edition.
        :type price: str
        """

        self._price = price

    @property
    def reserve_percentage(self) -> str:
        """Gets the reserve_percentage of this Edition.


        :return: The reserve_percentage of this Edition.
        :rtype: str
        """
        return self._reserve_percentage

    @reserve_percentage.setter
    def reserve_percentage(self, reserve_percentage: str):
        """Sets the reserve_percentage of this Edition.


        :param reserve_percentage: The reserve_percentage of this Edition.
        :type reserve_percentage: str
        """

        self._reserve_percentage = reserve_percentage

    @property
    def collection(self) -> CollectionListable:
        """Gets the collection of this Edition.


        :return: The collection of this Edition.
        :rtype: CollectionListable
        """
        return self._collection

    @collection.setter
    def collection(self, collection: CollectionListable):
        """Sets the collection of this Edition.


        :param collection: The collection of this Edition.
        :type collection: CollectionListable
        """

        self._collection = collection

    @property
    def drop_editions(self) -> List[DropEdition]:
        """Gets the drop_editions of this Edition.


        :return: The drop_editions of this Edition.
        :rtype: List[DropEdition]
        """
        return self._drop_editions

    @drop_editions.setter
    def drop_editions(self, drop_editions: List[DropEdition]):
        """Sets the drop_editions of this Edition.


        :param drop_editions: The drop_editions of this Edition.
        :type drop_editions: List[DropEdition]
        """

        self._drop_editions = drop_editions

    @property
    def nfts(self) -> List[Nft]:
        """Gets the nfts of this Edition.


        :return: The nfts of this Edition.
        :rtype: List[Nft]
        """
        return self._nfts

    @nfts.setter
    def nfts(self, nfts: List[Nft]):
        """Sets the nfts of this Edition.


        :param nfts: The nfts of this Edition.
        :type nfts: List[Nft]
        """

        self._nfts = nfts

    @property
    def nfts_minted(self) -> int:
        """Gets the nfts_minted of this Edition.


        :return: The nfts_minted of this Edition.
        :rtype: int
        """
        return self._nfts_minted

    @nfts_minted.setter
    def nfts_minted(self, nfts_minted: int):
        """Sets the nfts_minted of this Edition.


        :param nfts_minted: The nfts_minted of this Edition.
        :type nfts_minted: int
        """

        self._nfts_minted = nfts_minted

    @property
    def nfts_for_sale(self) -> int:
        """Gets the nfts_for_sale of this Edition.


        :return: The nfts_for_sale of this Edition.
        :rtype: int
        """
        return self._nfts_for_sale

    @nfts_for_sale.setter
    def nfts_for_sale(self, nfts_for_sale: int):
        """Sets the nfts_for_sale of this Edition.


        :param nfts_for_sale: The nfts_for_sale of this Edition.
        :type nfts_for_sale: int
        """

        self._nfts_for_sale = nfts_for_sale
