# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.api_response import ApiResponse  # noqa: F401,E501
from swagger_server.models.list_collections import ListCollections  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        code: int = None,
        message: str = None,
        data: ListCollections = None,
        error: str = None,
    ):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param code: The code of this InlineResponse2003.  # noqa: E501
        :type code: int
        :param message: The message of this InlineResponse2003.  # noqa: E501
        :type message: str
        :param data: The data of this InlineResponse2003.  # noqa: E501
        :type data: ListCollections
        :param error: The error of this InlineResponse2003.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            "code": int,
            "message": str,
            "data": ListCollections,
            "error": str,
        }

        self.attribute_map = {
            "code": "code",
            "message": "message",
            "data": "data",
            "error": "error",
        }
        self._code = code
        self._message = message
        self._data = data
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse2003":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse2003.


        :return: The code of this InlineResponse2003.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse2003.


        :param code: The code of this InlineResponse2003.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse2003.


        :return: The message of this InlineResponse2003.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse2003.


        :param message: The message of this InlineResponse2003.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> ListCollections:
        """Gets the data of this InlineResponse2003.


        :return: The data of this InlineResponse2003.
        :rtype: ListCollections
        """
        return self._data

    @data.setter
    def data(self, data: ListCollections):
        """Sets the data of this InlineResponse2003.


        :param data: The data of this InlineResponse2003.
        :type data: ListCollections
        """

        self._data = data

    @property
    def error(self) -> str:
        """Gets the error of this InlineResponse2003.


        :return: The error of this InlineResponse2003.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this InlineResponse2003.


        :param error: The error of this InlineResponse2003.
        :type error: str
        """

        self._error = error
