# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.serie_listable import SerieListable  # noqa: F401,E501
from swagger_server import util


class ListSeries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, series: List[SerieListable] = None, total_pages: int = None
    ):  # noqa: E501
        """ListSeries - a model defined in Swagger

        :param series: The series of this ListSeries.  # noqa: E501
        :type series: List[SerieListable]
        :param total_pages: The total_pages of this ListSeries.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {"series": List[SerieListable], "total_pages": int}

        self.attribute_map = {"series": "series", "total_pages": "total_pages"}
        self._series = series
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> "ListSeries":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListSeries of this ListSeries.  # noqa: E501
        :rtype: ListSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def series(self) -> List[SerieListable]:
        """Gets the series of this ListSeries.


        :return: The series of this ListSeries.
        :rtype: List[SerieListable]
        """
        return self._series

    @series.setter
    def series(self, series: List[SerieListable]):
        """Sets the series of this ListSeries.


        :param series: The series of this ListSeries.
        :type series: List[SerieListable]
        """

        self._series = series

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this ListSeries.


        :return: The total_pages of this ListSeries.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this ListSeries.


        :param total_pages: The total_pages of this ListSeries.
        :type total_pages: int
        """

        self._total_pages = total_pages
