# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.edition_error import EditionError  # noqa: F401,E501
from swagger_server import util


class ListEditionErrors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, edition_errors: List[EditionError] = None, total_pages: int = None
    ):  # noqa: E501
        """ListEditionErrors - a model defined in Swagger

        :param edition_errors: The edition_errors of this ListEditionErrors.  # noqa: E501
        :type edition_errors: List[EditionError]
        :param total_pages: The total_pages of this ListEditionErrors.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {"edition_errors": List[EditionError], "total_pages": int}

        self.attribute_map = {
            "edition_errors": "edition_errors",
            "total_pages": "total_pages",
        }
        self._edition_errors = edition_errors
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> "ListEditionErrors":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListEditionErrors of this ListEditionErrors.  # noqa: E501
        :rtype: ListEditionErrors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edition_errors(self) -> List[EditionError]:
        """Gets the edition_errors of this ListEditionErrors.


        :return: The edition_errors of this ListEditionErrors.
        :rtype: List[EditionError]
        """
        return self._edition_errors

    @edition_errors.setter
    def edition_errors(self, edition_errors: List[EditionError]):
        """Sets the edition_errors of this ListEditionErrors.


        :param edition_errors: The edition_errors of this ListEditionErrors.
        :type edition_errors: List[EditionError]
        """

        self._edition_errors = edition_errors

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this ListEditionErrors.


        :return: The total_pages of this ListEditionErrors.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this ListEditionErrors.


        :param total_pages: The total_pages of this ListEditionErrors.
        :type total_pages: int
        """

        self._total_pages = total_pages
