# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.nft import Nft  # noqa: F401,E501
from swagger_server import util


class ListNfts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, nfts: List[Nft] = None, total_pages: int = None):  # noqa: E501
        """ListNfts - a model defined in Swagger

        :param nfts: The nfts of this ListNfts.  # noqa: E501
        :type nfts: List[Nft]
        :param total_pages: The total_pages of this ListNfts.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {"nfts": List[Nft], "total_pages": int}

        self.attribute_map = {"nfts": "nfts", "total_pages": "total_pages"}
        self._nfts = nfts
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> "ListNfts":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListNfts of this ListNfts.  # noqa: E501
        :rtype: ListNfts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nfts(self) -> List[Nft]:
        """Gets the nfts of this ListNfts.


        :return: The nfts of this ListNfts.
        :rtype: List[Nft]
        """
        return self._nfts

    @nfts.setter
    def nfts(self, nfts: List[Nft]):
        """Sets the nfts of this ListNfts.


        :param nfts: The nfts of this ListNfts.
        :type nfts: List[Nft]
        """

        self._nfts = nfts

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this ListNfts.


        :return: The total_pages of this ListNfts.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this ListNfts.


        :param total_pages: The total_pages of this ListNfts.
        :type total_pages: int
        """

        self._total_pages = total_pages
