# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Mint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, quantity: int = None):  # noqa: E501
        """Mint - a model defined in Swagger

        :param quantity: The quantity of this Mint.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {"quantity": int}

        self.attribute_map = {"quantity": "quantity"}
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> "Mint":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Mint of this Mint.  # noqa: E501
        :rtype: Mint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self) -> int:
        """Gets the quantity of this Mint.


        :return: The quantity of this Mint.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this Mint.


        :param quantity: The quantity of this Mint.
        :type quantity: int
        """

        self._quantity = quantity
