# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, success: bool = None):  # noqa: E501
        """SuccessResponse - a model defined in Swagger

        :param success: The success of this SuccessResponse.  # noqa: E501
        :type success: bool
        """
        self.swagger_types = {"success": bool}

        self.attribute_map = {"success": "success"}
        self._success = success

    @classmethod
    def from_dict(cls, dikt) -> "SuccessResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse of this SuccessResponse.  # noqa: E501
        :rtype: SuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this SuccessResponse.


        :return: The success of this SuccessResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this SuccessResponse.


        :param success: The success of this SuccessResponse.
        :type success: bool
        """

        self._success = success
