"""change_edition_enumerations_to_string

Revision ID: f27e256d11c1
Revises: 08022051c993
Create Date: 2022-01-20 13:13:12.851824

"""
from alembic import op
import sqlalchemy as sa
from migrations.utils import (
    exists_table,
    exists_column,
)


# revision identifiers, used by Alembic.
revision = "f27e256d11c1"
down_revision = "08022051c993"
branch_labels = None
depends_on = None

__table_name: str = "editions"
__type: str = "type"
__design_slot: str = "design_slot"
__rarity: str = "rarity"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if exists_table(__table_name):
        if exists_column(__table_name, __type):
            op.alter_column(
                table_name=__table_name,
                column_name=__type,
                nullable=False,
                type_=sa.String(100),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__type, sa.String(length=100), unique=False),
            )
        if exists_column(__table_name, __design_slot):
            op.alter_column(
                table_name=__table_name,
                column_name=__design_slot,
                nullable=False,
                type_=sa.String(100),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__design_slot, sa.String(length=100), unique=False),
            )
        if exists_column(__table_name, __rarity):
            op.alter_column(
                table_name=__table_name,
                column_name=__rarity,
                nullable=False,
                type_=sa.String(100),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__rarity, sa.String(length=100), unique=False),
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if exists_table(__table_name):
        if exists_column(__table_name, __type):
            op.alter_column(
                table_name=__table_name,
                column_name=__type,
                nullable=False,
                type_=sa.Enum(
                    "EDITION_TYPE_AVATAR_NIL",
                    "EDITION_TYPE_AVATAR_STATUE",
                    "EDITION_TYPE_AVATAR_WEARABLE",
                    name="editiontype",
                ),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__type, sa.String(length=100), unique=False),
            )
        if exists_column(__table_name, __design_slot):
            op.alter_column(
                table_name=__table_name,
                column_name=__design_slot,
                nullable=False,
                type_=sa.Enum(
                    "EDITION_DESIGN_SLOT_NIL",
                    "EDITION_DESIGN_SLOT_GLASSES",
                    "EDITION_DESIGN_SLOT_HELMET",
                    "EDITION_DESIGN_SLOT_MASK",
                    "EDITION_DESIGN_SLOT_SHIRT",
                    "EDITION_DESIGN_SLOT_JACKET",
                    "EDITION_DESIGN_SLOT_PANTS",
                    "EDITION_DESIGN_SLOT_SHOES",
                    name="designslot",
                ),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__design_slot, sa.String(length=100), unique=False),
            )
        if exists_column(__table_name, __rarity):
            op.alter_column(
                table_name=__table_name,
                column_name=__rarity,
                nullable=False,
                type_=sa.Enum(
                    "EDITION_RARITY_NIL",
                    "EDITION_RARITY_UNIQUE",
                    "EDITION_RARITY_LEGENDARY",
                    "EDITION_RARITY_EPIC",
                    "EDITION_RARITY_RARE",
                    "EDITION_RARITY_STANDARD",
                    "EDITION_RARITY_COMMON",
                    name="editionrarity",
                ),
            )
        else:
            op.add_column(
                __table_name,
                sa.Column(__rarity, sa.String(length=100), unique=False),
            )
