from enum import Enum


class DesignSlot(Enum):
    """Type enum for design slots"""

    EDITION_DESIGN_SLOT_NIL = "EDITION_DESIGN_SLOT_NIL"
    EDITION_DESIGN_SLOT_GLASSES = "EDITION_DESIGN_SLOT_GLASSES"
    EDITION_DESIGN_SLOT_HELMET = "EDITION_DESIGN_SLOT_HELMET"
    EDITION_DESIGN_SLOT_MASK = "EDITION_DESIGN_SLOT_MASK"
    EDITION_DESIGN_SLOT_SHIRT = "EDITION_DESIGN_SLOT_SHIRT"
    EDITION_DESIGN_SLOT_JACKET = "EDITION_DESIGN_SLOT_JACKET"
    EDITION_DESIGN_SLOT_PANTS = "EDITION_DESIGN_SLOT_PANTS"
    EDITION_DESIGN_SLOT_SHOES = "EDITION_DESIGN_SLOT_SHOES"
