from enum import Enum


class EditionRarity(Enum):
    EDITION_RARITY_NIL = "EDITION_RARITY_NIL"
    EDITION_RARITY_UNIQUE = "EDITION_RARITY_UNIQUE"
    EDITION_RARITY_LEGENDARY = "EDITION_RARITY_LEGENDARY"
    EDITION_RARITY_EPIC = "EDITION_RARITY_EPIC"
    EDITION_RARITY_RARE = "EDITION_RARITY_RARE"
    EDITION_RARITY_STANDARD = "EDITION_RARITY_STANDARD"
    EDITION_RARITY_COMMON = "EDITION_RARITY_COMMON"
